[advisories]
version = 2
ignore = [
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = [
    { name = "openssl" }
]

[bans.workspace-dependencies]
duplicates = 'deny'
include-path-dependencies = true
unused = 'allow'

[licenses]
version = 2
confidence-threshold = 0.9
private = { ignore = true }

allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
    "CDLA-Permissive-2.0"
]

exceptions = [
    { allow = ["CC0-1.0"], name = "tiny-keccak" },
    { allow = ["OpenSSL"], name = "ring" },
]

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]

# Actually "ISC-style"
[[licenses.clarify]]
name = "rustls-webpki"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    "https://github.com/paradigmxyz/reth.git"
]
