name = "Base"
id = 8453

da_pre_verification_gas = true
da_gas_oracle_type = "OPTIMISM_BEDROCK"
da_gas_oracle_contract_address = "0x420000000000000000000000000000000000000F"

max_transaction_size_bytes = 130000

priority_fee_oracle_type = "USAGE_BASED"
min_max_priority_fee_per_gas = 1000000
congestion_trigger_usage_ratio_threshold = 0.20
