name = "Base"
id = 8453

calldata_pre_verification_gas = true
l1_gas_oracle_contract_type = "OPTIMISM_BEDROCK"
l1_gas_oracle_contract_address = "0x420000000000000000000000000000000000000F"
include_l1_gas_in_gas_limit = false

max_transaction_size_bytes = 130000

priority_fee_oracle_type = "USAGE_BASED"
min_max_priority_fee_per_gas = "0x0F4240" # 1_000_000
congestion_trigger_usage_ratio_threshold = 0.25
