base = "ethereum"

name = "Ethereum Sepolia"
id = 11155111

flashbots_relay_url = "https://relay-sepolia.flashbots.net"
flashbots_status_url = "https://protect-sepolia.flashbots.net/tx/"

min_max_priority_fee_per_gas = 100000000
