name = "Optimism"
id = 10

calldata_pre_verification_gas = true
l1_gas_oracle_contract_type = "OPTIMISM_BEDROCK"
l1_gas_oracle_contract_address = "0x420000000000000000000000000000000000000F"
include_l1_gas_in_gas_limit = false

priority_fee_oracle_type = "USAGE_BASED"
min_max_priority_fee_per_gas = "0x0186A0" # 100_000
max_transaction_size_bytes = 90000
