[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache'
solc_version = '0.8.26'
optimizer = true
optimizer_runs = 200
evm_version = 'paris'

remappings = [
    '@account-abstraction=lib/account-abstraction/contracts/',
    '@openzeppelin=lib/openzeppelin-contracts/',
    'common=../common/src'
]
