on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

name: PR title check
jobs:
  pr-semantic-check:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
